#ifndef __MM_H__
#define __MM_H__
#include <stddef.h>
#include <plic.h>
#include <uart.h>
/// @{ @name 物理内存布局和物理地址操作
#define PLIC_END_ADDRESS (PLIC_START + PLIC_LENGTH)
#define UART_END_ADDRESS (PLIC_END_ADDRESS + UART_LENGTH)

#define PLIC_PRIORITY_ADDRESS (PLIC_START + PLIC_PRIORITY)
#define PLIC_PENDING_ADDRESS (PLIC_START + PLIC_PENDING)
#define PLIC_ENABLE_ADDRESS (PLIC_START + PLIC_ENABLE)
#define PLIC_THRESHOLD_ADDRESS (PLIC_PENDING_ADDRESS + PLIC_THRESHOLD)
#define PLIC_CLAIM_ADDRESS (PLIC_PENDING_ADDRESS + PLIC_CLAIM)
#define PLIC_COMPLETE_ADDRESS (PLIC_PENDING_ADDRESS + PLIC_COMPLETE)

#define UART_RBR_ADDR (UART_START + UART_RBR)
#define UART_THR_ADDR (UART_START + UART_THR)
#define UART_DLL_ADDR (UART_START + UART_DLL)
#define UART_IER_ADDR (UART_START + UART_IER)
#define UART_DLM_ADDR (UART_START + UART_DLM)
#define UART_IIR_ADDR (UART_START + UART_IIR)
#define UART_FCR_ADDR (UART_START + UART_FCR)
#define UART_LCR_ADDR (UART_START + UART_LCR)
#define UART_MCR_ADDR (UART_START + UART_MCR)
#define UART_LSR_ADDR (UART_START + UART_LSR)
#define UART_MSR_ADDR (UART_START + UART_MSR)
#define UART_SCR_ADDR (UART_START + UART_SCR)

#endif